trailingComma: es5
tabWidth: 2
semi: true
singleQuote: true
printWidth: 80
arrowParens: always
endOfLine: lf
bracketSpacing: true
jsxSingleQuote: true
quoteProps: as-needed
htmlWhitespaceSensitivity: css